### ISSUE TITLE
QA [부서 선택 페이지]

### ISSUE THREAD

**Issue by indianaPoly** [yourssu/Yourssu-landing-page#37]
부서 선택 페이지 QA 입니다.

**Comment by indianaPoly** [comment]
문제 사항 : FAQ 반응형 제작 및 FAQ 답변 여부 제작

**Comment by AAminha** [comment]
텍스트 하나하나에 스크롤 바가 보임
![image](https://github.com/yourssu/Yourssu-landing-page/assets/87255791/7a88a5b6-ab43-4226-986c-a5e4054fc4f4)

**Comment by AAminha** [comment]
폰트 지정이 안 되어 있는 것 같음
![image](https://github.com/yourssu/Yourssu-landing-page/assets/87255791/1d76a737-5a21-4d3c-9d6c-49518186e025)

**Comment by AAminha** [comment]
검색바 input 포커즈 스타일 삭제
![image](https://github.com/yourssu/Yourssu-landing-page/assets/87255791/b6ea19b9-55f8-4e91-bc5c-6aa8078a90dc)

**Comment by indianaPoly** [comment]
<img width="489" alt="스크린샷 2024-02-25 오후 1 46 51" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/6b511e50-db39-4261-800f-3ceac39b2947">

피그마 수정사항에 따라 변경 필요

**Comment by indianaPoly** [comment]
<img width="726" alt="스크린샷 2024-02-25 오후 1 48 00" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/906431fe-7b3e-446e-9ced-26a3aece9026">

지원하기 클릭시 아래 카드 컴포넌트가 나오는 것으로 스크롤 이동 시켜야 함.

**Comment by indianaPoly** [comment]
<img width="722" alt="스크린샷 2024-02-25 오후 1 56 04" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/6eae9bcd-9f4c-4f08-883a-59d02669a1d3">

글자 줄 넘김 있으면 안됨.

**Comment by indianaPoly** [comment]
<img width="722" alt="스크린샷 2024-02-25 오후 1 57 40" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/0310225f-4963-4d96-9ed8-a7f4e929a517">

검색 끝 부분과 카드 섹션 끝 부분이 일치해야됩니다

**Comment by indianaPoly** [comment]
카드 섹션 hover 시에 애니메이션 추가
