### ISSUE TITLE
QA [부서 상세 페이지]

### ISSUE THREAD

**Issue by indianaPoly** [yourssu/Yourssu-landing-page#38]
부서 상세 페이지 QA 입니다.

**Comment by AAminha** [comment]
첫 로딩 시 하단 지원하기 버튼이 보임

**Comment by AAminha** [comment]
Seo 추가

**Comment by indianaPoly** [comment]
<img width="722" alt="스크린샷 2024-02-25 오후 2 17 07" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/1a2067ad-aad0-4a00-893d-df5006c70673">

해당 지원하기 누르면 구글이나 네이버로 이동해요!

**Comment by indianaPoly** [comment]
<img width="411" alt="스크린샷 2024-02-25 오후 2 33 26" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/13cfff18-7e55-4cb5-a2cc-11c308db2ba3">

해당 버튼이 뒷 배경이 피그마에서는 흐릿하게 보이는 반면에 모바일에 접속을해서 보게 되면 내용이 다 보입니다..!

**Comment by indianaPoly** [comment]
<img width="444" alt="스크린샷 2024-02-25 오후 2 38 50" src="https://github.com/yourssu/Yourssu-landing-page/assets/95522176/9b28d7c4-5272-4f1b-81b6-dd0e53e6711c">
![KakaoTalk_Photo_2024-02-25-14-41-09](https://github.com/yourssu/Yourssu-landing-page/assets/95522176/7b218f3e-4d7e-443d-974e-893d36194835)

모바일의 경우에 로드 투 프로 배경색이 흰색으로 나오는데 저만 그런걸까요 ?!

**Comment by AAminha** [comment]
> 모바일의 경우에 로드 투 프로 배경색이 흰색으로 나오는데 저만 그런걸까요 ?!
제 모바일(안드)는 잘 나오는데 방금 아이패드로 확인하니까 안 나오네요^_^ (아오)

**Comment by AAminha** [comment]
> 해당 버튼이 뒷 배경이 피그마에서는 흐릿하게 보이는 반면에 모바일에 접속을해서 보게 되면 내용이 다 보입니다..!

세상에... 이런 디테일이 있었다니.. 확인 너무 감사합니다ㅠㅠ
